# Generated by Django 3.0.3 on 2020-03-11 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start', models.DateField(db_index=True, verbose_name='Дата начала')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='О себе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='О себе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи на курс')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Стоимость с учетом скидок')),
                ('paid', models.BooleanField(default=False, verbose_name='Курс оплачен')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_app.Course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_app.Student', verbose_name='Студент')),
            ],
            options={
                'db_table': 'education_app_course_entry',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_app.Course', verbose_name='Курс')),
            ],
            options={
                'db_table': 'education_app_course_admin',
                'unique_together': {('course', 'admin')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='admins',
            field=models.ManyToManyField(through='education_app.CourseAdmin', to=settings.AUTH_USER_MODEL, verbose_name='Администраторы'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, through='education_app.CourseEntry', to='education_app.Student', verbose_name='Студенты'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start', models.DateTimeField(verbose_name='Дата и время начала')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_app.Course', verbose_name='Курс')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='education_app.Teacher', verbose_name='Преподаватель')),
            ],
            options={
                'ordering': ['start', 'id'],
                'index_together': {('course', 'start')},
            },
        ),
    ]
