# Generated by Django 3.0.3 on 2020-03-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0002_auto_20200312_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Удален'),
        ),
    ]
