# Generated by Django 3.0.3 on 2020-02-27 19:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0002_course_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя', max_length=200)),
                ('surname', models.CharField(help_text='Фамилия', max_length=200)),
                ('joined', models.DateField(help_text='Дата начала')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='created',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='', help_text='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start',
            field=models.DateField(default=datetime.date(2020, 2, 27), help_text='Дата начала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Название', max_length=200),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='education_app.User')),
            ],
            bases=('education_app.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='education_app.User')),
            ],
            bases=('education_app.user',),
        ),
        migrations.AddField(
            model_name='course',
            name='admins',
            field=models.ManyToManyField(related_name='_course_admins_+', to='education_app.User'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Описание')),
                ('start', models.DateTimeField(help_text='Дата и время начала')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_app.Course')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education_app.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Дата записи на курс')),
                ('discount', models.IntegerField(blank=True, help_text='Процент скидки')),
                ('paid', models.BooleanField(help_text='Курс оплачен')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_app.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_app.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='education_app.CourseEntry', to='education_app.Student'),
        ),
    ]
