# Generated by Django 3.0.3 on 2020-03-11 23:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education_app', '0003_course_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseadmin',
            old_name='admin',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='courseadmin',
            unique_together={('course', 'user')},
        ),
    ]
