# Generated by Django 3.0.3 on 2020-02-27 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0003_auto_20200227_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.TextField(default=None, help_text='Резюме'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='resume',
            field=models.TextField(default=None, help_text='Резюме'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='admins',
            field=models.ManyToManyField(db_table='course_admin', related_name='_course_admins_+', to='education_app.User'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Описание', null=True),
        ),
        migrations.AlterField(
            model_name='courseentry',
            name='discount',
            field=models.IntegerField(blank=True, help_text='Процент скидки', null=True),
        ),
        migrations.AlterField(
            model_name='courseentry',
            name='paid',
            field=models.BooleanField(default=False, help_text='Курс оплачен'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='Описание', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='education_app.Teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='joined',
            field=models.DateField(auto_now_add=True, help_text='Присоединился'),
        ),
        migrations.AlterModelTable(
            name='courseentry',
            table='course_entry',
        ),
    ]
