# Generated by Django 3.0.3 on 2020-02-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0004_auto_20200228_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseentry',
            name='discount',
        ),
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.IntegerField(blank=True, help_text='Стоимость', null=True),
        ),
        migrations.AddField(
            model_name='courseentry',
            name='cost',
            field=models.IntegerField(blank=True, help_text='Стоимость с учетом скидок', null=True),
        ),
    ]
