# Generated by Django 3.0.3 on 2020-03-11 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education_app', '0004_auto_20200312_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='О себе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='courseadmin',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='education_app.Administrator', verbose_name='Администратор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='admins',
            field=models.ManyToManyField(through='education_app.CourseAdmin', to='education_app.Administrator', verbose_name='Администраторы'),
        ),
        migrations.AlterUniqueTogether(
            name='courseadmin',
            unique_together={('course', 'admin')},
        ),
        migrations.RemoveField(
            model_name='courseadmin',
            name='user',
        ),
    ]
