# Generated by Django 3.0.3 on 2020-02-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0005_auto_20200228_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start',
            field=models.DateField(db_index=True, help_text='Дата начала'),
        ),
        migrations.AlterUniqueTogether(
            name='courseentry',
            unique_together={('student', 'course')},
        ),
        migrations.AlterIndexTogether(
            name='lesson',
            index_together={('course', 'start')},
        ),
    ]
