# Generated by Django 3.0.3 on 2020-03-11 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0007_auto_20200312_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseadmin',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education_app.Administrator', verbose_name='Администратор'),
        ),
    ]
