# Generated by Django 3.0.3 on 2020-03-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0009_auto_20200312_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseadmin',
            name='start',
            field=models.DateField(auto_now=True, verbose_name='Дата начала'),
        ),
    ]
